repos:
  - repo: local
    hooks:
      - id: count-and-update-hyperlinks
        name: Count and Update Hyperlinks
        entry: python3 scripts/count_entries.py
        language: system
        files: ^docs/.*\.md$
      - id: bold-hyperlinks
        name: Bold Hyperlinks
        entry: python3 scripts/bold_hyperlinks.py
        language: system
        files: ^docs/.*\.md$