title: CADD_Vault
description: >- # this means to ignore newlines until "baseurl:"
  An open-source collection of resources on computer-aided drug design.
baseurl: "" # the subpath of your site, e.g., /blog
url: "" # the base hostname & protocol for your site, e.g., http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
